set -g prefix C-a

unbind-key C-b
bind-key C-a send-prefix

bind -r Tab select-pane -t :.+

# allow mouse-navigation through panes
set -g mouse on

# allow vi keybindings in copy mode. ntfs -> don't really understand this
setw -g mode-keys vi

# vim-like pane switching (theprimeagen)
bind -r z select-pane -U
bind -r v select-pane -D
bind -r m select-pane -L
bind -r w select-pane -R

# split window horizontally
unbind-key split-window
bind - split-window -v -c "#{pane_current_path}"
